# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_material.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(287, 248)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 261, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 287, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "添加材料"))
        self.label.setText(_translate("MainWindow", "产品名称："))
        self.comboBox.setItemText(0, _translate("MainWindow", "12v电源线"))
        self.comboBox.setItemText(1, _translate("MainWindow", "视频线1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "无线接收模块"))
        self.comboBox.setItemText(3, _translate("MainWindow", "交流电源线"))
        self.comboBox.setItemText(4, _translate("MainWindow", "12VDC线"))
        self.comboBox.setItemText(5, _translate("MainWindow", "视频线2"))
        self.comboBox.setItemText(6, _translate("MainWindow", "喇叭线"))
        self.comboBox.setItemText(7, _translate("MainWindow", "按键板连接线"))
        self.comboBox.setItemText(8, _translate("MainWindow", "黑色电源三孔插座"))
        self.comboBox.setItemText(9, _translate("MainWindow", "20W开关电源"))
        self.comboBox.setItemText(10, _translate("MainWindow", "电源线"))
        self.comboBox.setItemText(11, _translate("MainWindow", "手动调焦镜头"))
        self.comboBox.setItemText(12, _translate("MainWindow", "摄像头模块组（IR_CUT组件）"))
        self.comboBox.setItemText(13, _translate("MainWindow", "铜柱（通孔）"))
        self.comboBox.setItemText(14, _translate("MainWindow", "铜柱（非通孔）"))
        self.comboBox.setItemText(15, _translate("MainWindow", "螺丝"))
        self.comboBox.setItemText(16, _translate("MainWindow", "石英片"))
        self.comboBox.setItemText(17, _translate("MainWindow", "小橡胶圈"))
        self.comboBox.setItemText(18, _translate("MainWindow", "大像胶圈"))
        self.comboBox.setItemText(19, _translate("MainWindow", "显示屏"))
        self.comboBox.setItemText(20, _translate("MainWindow", "扫码枪"))
        self.comboBox.setItemText(21, _translate("MainWindow", "摄像头及主板"))
        self.comboBox.setItemText(22, _translate("MainWindow", "内存卡"))
        self.comboBox.setItemText(23, _translate("MainWindow", "透明二极管"))
        self.label_2.setText(_translate("MainWindow", "添加数量： "))
        self.pushButton.setText(_translate("MainWindow", "添加"))

